INSERT INTO drivingschool.jiaxiaocheliang (addtime,chepaihao,cheliangmingcheng,cheliangleixing,kemu,cheliangtupian,cheliangxiangqing,jiaolianzhanghao,jiaolianxingming) VALUES
	 ('2023-03-11 19:58:59','车牌号1','车辆名称1','训练车','科目二','upload/jiaxiaocheliang_cheliangtupian1.jpg,upload/jiaxiaocheliang_cheliangtupian2.jpg,upload/jiaxiaocheliang_cheliangtupian3.jpg','车辆info1','Coach account1','Coach Name1'),
	 ('2023-03-11 19:58:59','车牌号2','车辆名称2','训练车','科目二','upload/jiaxiaocheliang_cheliangtupian2.jpg,upload/jiaxiaocheliang_cheliangtupian3.jpg,upload/jiaxiaocheliang_cheliangtupian4.jpg','车辆info2','Coach account2','Coach Name2'),
	 ('2023-03-11 19:58:59','车牌号3','车辆名称3','训练车','科目二','upload/jiaxiaocheliang_cheliangtupian3.jpg,upload/jiaxiaocheliang_cheliangtupian4.jpg,upload/jiaxiaocheliang_cheliangtupian5.jpg','车辆info3','Coach account3','Coach Name3'),
	 ('2023-03-11 19:58:59','车牌号4','车辆名称4','训练车','科目二','upload/jiaxiaocheliang_cheliangtupian4.jpg,upload/jiaxiaocheliang_cheliangtupian5.jpg,upload/jiaxiaocheliang_cheliangtupian6.jpg','车辆info4','Coach account4','Coach Name4'),
	 ('2023-03-11 19:58:59','车牌号5','车辆名称5','训练车','科目二','upload/jiaxiaocheliang_cheliangtupian5.jpg,upload/jiaxiaocheliang_cheliangtupian6.jpg,upload/jiaxiaocheliang_cheliangtupian7.jpg','车辆info5','Coach account5','Coach Name5'),
	 ('2023-03-11 19:58:59','车牌号6','车辆名称6','训练车','科目二','upload/jiaxiaocheliang_cheliangtupian6.jpg,upload/jiaxiaocheliang_cheliangtupian7.jpg,upload/jiaxiaocheliang_cheliangtupian8.jpg','车辆info6','Coach account6','Coach Name6'),
	 ('2023-03-11 19:58:59','车牌号7','车辆名称7','训练车','科目二','upload/jiaxiaocheliang_cheliangtupian7.jpg,upload/jiaxiaocheliang_cheliangtupian8.jpg,upload/jiaxiaocheliang_cheliangtupian9.jpg','车辆info7','Coach account7','Coach Name7'),
	 ('2023-03-11 19:58:59','车牌号8','车辆名称8','训练车','科目二','upload/jiaxiaocheliang_cheliangtupian8.jpg,upload/jiaxiaocheliang_cheliangtupian9.jpg,upload/jiaxiaocheliang_cheliangtupian10.jpg','车辆info8','Coach account8','Coach Name8');
